project_name: 'DF_10sec_EP40_SS50_larger' 
train_epochs: 40
batch_size: 64
condition: True
sampling_steps: 50
beta_schedule: 'cosine'
ddim: False
seq_length: 10000
objective: 'pred_noise'
loss_function: 'l2'
lr: 0.0001
mix_precision: False
gradient_accumulate_every: 1
ema_decay: 0.995
inference_milestone: 'best'
denoise_timesteps: 
